### ISSUE TITLE
EPIC: replace exomiser p2p pipeline with semsimian

### ISSUE THREAD

**Issue by matentzn** [monarch-initiative/monarch-semantic-similarity-profiles#19]
- [X] Create a make pipeline to generate hp-hp mappings based on phenio (with 0.4 Jaccard threshold)
- [X] Create a make pipeline to generate hp-mp mappings based on phenio (with 0.4 Jaccard threshold)
- [X] Create a make pipeline to generate hp-zp mappings based on phenio (with 0.4 Jaccard threshold)
-  Create the following experimental goals (4 configs, 12 distinct semantic similarity profiles):
      - [ ] phenio ---> IC scores ---> semsimian  + IC ---> hp-hp, hp-mp, hp-zp profile (#18)
      - [ ] phenio + equivalence ---> IC scores ---> semsimian  + IC ---> hp-hp, hp-mp, hp-zp profile (#18)
      - [ ] phenio ---> semsimian --->  hp-hp, hp-mp, hp-zp profile
      - [ ] phenio ---> NEAT embeddings --> semsimian (cosine similarity) --->  hp-hp, hp-mp, hp-zp profile (#6)
 - [ ] Run exomiser with the default config and all of these three configs
 - [ ] Generate your new rank-changed plot
 - [ ] Present at PhEval meeting
